# Generated by Django 5.1 on 2024-08-28 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(default='Default Department', max_length=255, verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Statemp',
            fields=[
                ('statsid', models.AutoField(primary_key=True, serialize=False)),
                ('stutsname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Employee Status',
                'verbose_name_plural': 'Employee Statuses',
            },
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('suprid', models.AutoField(primary_key=True, serialize=False)),
                ('supname', models.CharField(error_messages={'required': 'Supervisor Name is required'}, max_length=100)),
                ('supnumber', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Supervisor',
                'verbose_name_plural': 'Supervisors',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empid', models.AutoField(primary_key=True, serialize=False)),
                ('empidn', models.PositiveIntegerField()),
                ('empname_eng', models.CharField(max_length=255)),
                ('empnumber', models.CharField(max_length=20)),
                ('othernumber', models.CharField(max_length=20)),
                ('empemail', models.EmailField(max_length=254)),
                ('birth_date', models.DateField(help_text="Enter the employee's date of birth", verbose_name='Date of Birth')),
                ('city', models.CharField(help_text="Select the employee's city", max_length=100, verbose_name='City')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="Select the employee's gender", max_length=1, verbose_name='Gender')),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married')], default='S', help_text="Select the employee's marital status", max_length=1, verbose_name='Marital Status')),
                ('jopt', models.CharField(blank=True, max_length=255, null=True)),
                ('joindate', models.DateField()),
                ('form_sent', models.BooleanField(default=False)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empapp.dept')),
                ('statsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empapp.statemp')),
                ('suprid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empapp.super')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
