# Generated by Django 5.1 on 2024-08-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Dammam', 'Dammam'), ('Khobar', 'Khobar'), ('Mecca', 'Mecca'), ('Medina', 'Medina'), ('Dhahran', 'Dhahran'), ('Buraidah', 'Buraidah'), ('Abha', 'Abha'), ('Khamis Mushait', 'Khamis Mushait'), ('Najran', 'Najran'), ('Hail', 'Hail'), ('Jizan', 'Jizan'), ('Jubail', 'Jubail'), ('Tabuk', 'Tabuk'), ('Sakaka', 'Sakaka'), ('Al Khobar', 'Al Khobar'), ('Yanbu', 'Yanbu'), ('Arar', 'Arar'), ('Qatif', 'Qatif'), ('Al Bahah', 'Al Bahah'), ('Al Ahsa', 'Al Ahsa'), ('Al Mubarraz', 'Al Mubarraz'), ('Sharurah', 'Sharurah'), ('Wadi ad-Dawasir', 'Wadi ad-Dawasir'), ('Al Kharj', 'Al Kharj'), ('Ras Tanura', 'Ras Tanura'), ('Al Jubail', 'Al Jubail'), ('Abqaiq', 'Abqaiq'), ('Al Qurayyat', 'Al Qurayyat'), ('Al Namas', 'Al Namas'), ('Al-Muwaih', 'Al-Muwaih'), ('Umluj', 'Umluj'), ('Al Khobar', 'Al Khobar'), ('Al Ula', 'Al Ula'), ('Al Artawiyah', 'Al Artawiyah'), ('Bisha', 'Bisha'), ('Khaybar', 'Khaybar')], default='Riyadh', help_text="Select the employee's city", max_length=30, verbose_name='City'),
        ),
    ]
